/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy):  5. 7.2023   Time (hh:mm): 10:26                        */
/*******************************************************************************/


#ifndef _SAMPLE_GRAPE_DISPLAY_1_RESOURCES_H_
#define _SAMPLE_GRAPE_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_32ARGB
#define DISPLAY_1_X_RESOLUTION 600
#define DISPLAY_1_Y_RESOLUTION 800
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_USED_COLOR_01 29
#define GX_COLOR_ID_USED_COLOR_02 30
#define GX_COLOR_ID_USED_COLOR_03 31
#define GX_COLOR_ID_USED_COLOR_04 32
#define GX_COLOR_ID_USED_COLOR_05 33
#define GX_COLOR_ID_USED_COLOR_06 34
#define GX_COLOR_ID_USED_COLOR_07 35
#define GX_COLOR_ID_USED_COLOR_08 36
#define GX_COLOR_ID_USED_COLOR_09 37
#define GX_COLOR_ID_USED_COLOR_10 38
#define GX_COLOR_ID_USED_COLOR_11 39
#define GX_COLOR_ID_USED_COLOR_12 40
#define GX_COLOR_ID_USED_COLOR_13 41
#define GX_COLOR_ID_USED_COLOR_14 42
#define GX_COLOR_ID_USED_COLOR_15 43
#define GX_COLOR_ID_USED_COLOR_16 44
#define GX_COLOR_ID_USED_COLOR_17 45
#define GX_COLOR_ID_USED_COLOR_18 46
#define GX_COLOR_ID_USED_COLOR_19 47
#define GX_COLOR_ID_USED_COLOR_20 48
#define GX_COLOR_ID_USED_COLOR_21 49
#define GX_COLOR_ID_USED_COLOR_22 50
#define GX_COLOR_ID_USED_COLOR_23 51
#define GX_COLOR_ID_USED_COLOR_24 52
#define GX_COLOR_ID_USED_COLOR_25 53
#define GX_COLOR_ID_USED_COLOR_26 54
#define GX_COLOR_ID_USED_COLOR_27 55
#define GX_COLOR_ID_USED_COLOR_28 56
#define GX_COLOR_ID_USED_COLOR_29 57
#define GX_COLOR_ID_BUTTON_COLOR 58
#define DISPLAY_1_COLOR_TABLE_SIZE 59

/* Font ID definitions                                                         */

#define GX_FONT_ID_SLIDER_FONT 4
#define GX_FONT_ID_SLIDER_FONT_2 5
#define DISPLAY_1_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BACKGROUND 5
#define GX_PIXELMAP_ID_BACKGROUND_1 6
#define GX_PIXELMAP_ID_BACKGROUND_2 7
#define GX_PIXELMAP_ID_BACKGROUND_3 8
#define GX_PIXELMAP_ID_BUTTON_DOWN_OFF 9
#define GX_PIXELMAP_ID_BUTTON_DOWN_ON 10
#define GX_PIXELMAP_ID_BUTTON_OVEN_OFF 11
#define GX_PIXELMAP_ID_BUTTON_OVEN_ON 12
#define GX_PIXELMAP_ID_BUTTON_START_OFF_1 13
#define GX_PIXELMAP_ID_BUTTON_START_ON_1 14
#define GX_PIXELMAP_ID_BUTTON_STOP_OFF_1 15
#define GX_PIXELMAP_ID_BUTTON_STOP_ON_1 16
#define GX_PIXELMAP_ID_BUTTON_THAW_OFF 17
#define GX_PIXELMAP_ID_BUTTON_THAW_ON 18
#define GX_PIXELMAP_ID_BUTTON_UP_OFF 19
#define GX_PIXELMAP_ID_BUTTON_UP_ON 20
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_HIGH_OFF 21
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_HIGH_ON 22
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_LOW_OFF 23
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_LOW_ON 24
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_MIDDLE_BUTTON_OFF 25
#define GX_PIXELMAP_ID_BUTTON_WATERLEVEL_MIDDLE_BUTTON_ON 26
#define GX_PIXELMAP_ID_CIRCLE_LABEL_AUTO 27
#define GX_PIXELMAP_ID_CIRCLE_LABEL_ECO 28
#define GX_PIXELMAP_ID_CIRCLE_LABEL_HARD 29
#define GX_PIXELMAP_ID_CIRCLE_LABEL_SOFT 30
#define GX_PIXELMAP_ID_CIRCLE_LABEL_WOOL 31
#define GX_PIXELMAP_ID_COLON 32
#define GX_PIXELMAP_ID_COLON_BIG 33
#define GX_PIXELMAP_ID_CURSOR_01 34
#define GX_PIXELMAP_ID_CURSOR_02 35
#define GX_PIXELMAP_ID_CURSOR_03 36
#define GX_PIXELMAP_ID_CURSOR_04 37
#define GX_PIXELMAP_ID_CURSOR_05 38
#define GX_PIXELMAP_ID_CURSOR_06 39
#define GX_PIXELMAP_ID_DOT 40
#define GX_PIXELMAP_ID_FRI 41
#define GX_PIXELMAP_ID_HOME_OFF 42
#define GX_PIXELMAP_ID_HOME_ON 43
#define GX_PIXELMAP_ID_HONE_ON 44
#define GX_PIXELMAP_ID_ICON_BACK 45
#define GX_PIXELMAP_ID_INFO_OFF 46
#define GX_PIXELMAP_ID_INFO_ON 47
#define GX_PIXELMAP_ID_LOGO_RENESAS 48
#define GX_PIXELMAP_ID_MICROWAVE_OFF 49
#define GX_PIXELMAP_ID_MICROWAVE_ON 50
#define GX_PIXELMAP_ID_MINUS 51
#define GX_PIXELMAP_ID_MINUS_1 52
#define GX_PIXELMAP_ID_MON 53
#define GX_PIXELMAP_ID_MOUSE_ICON 54
#define GX_PIXELMAP_ID_MOVIE_OFF 55
#define GX_PIXELMAP_ID_MOVIE_ON 56
#define GX_PIXELMAP_ID_N_0 57
#define GX_PIXELMAP_ID_N_1 58
#define GX_PIXELMAP_ID_N_2 59
#define GX_PIXELMAP_ID_N_3 60
#define GX_PIXELMAP_ID_N_4 61
#define GX_PIXELMAP_ID_N_5 62
#define GX_PIXELMAP_ID_N_6 63
#define GX_PIXELMAP_ID_N_7 64
#define GX_PIXELMAP_ID_N_8 65
#define GX_PIXELMAP_ID_N_9 66
#define GX_PIXELMAP_ID_NB_0 67
#define GX_PIXELMAP_ID_NB_1 68
#define GX_PIXELMAP_ID_NB_2 69
#define GX_PIXELMAP_ID_NB_3 70
#define GX_PIXELMAP_ID_NB_4 71
#define GX_PIXELMAP_ID_NB_5 72
#define GX_PIXELMAP_ID_NB_6 73
#define GX_PIXELMAP_ID_NB_7 74
#define GX_PIXELMAP_ID_NB_8 75
#define GX_PIXELMAP_ID_NB_9 76
#define GX_PIXELMAP_ID_O_0 77
#define GX_PIXELMAP_ID_O_1 78
#define GX_PIXELMAP_ID_O_2 79
#define GX_PIXELMAP_ID_O_3 80
#define GX_PIXELMAP_ID_O_4 81
#define GX_PIXELMAP_ID_O_5 82
#define GX_PIXELMAP_ID_O_6 83
#define GX_PIXELMAP_ID_O_7 84
#define GX_PIXELMAP_ID_O_8 85
#define GX_PIXELMAP_ID_O_9 86
#define GX_PIXELMAP_ID_POINTER 87
#define GX_PIXELMAP_ID_POINTER_OFF 88
#define GX_PIXELMAP_ID_POPUP_500X200 89
#define GX_PIXELMAP_ID_REFRIGERATOR_OFF 90
#define GX_PIXELMAP_ID_REFRIGERATOR_ON 91
#define GX_PIXELMAP_ID_RENESAS_LOGOMARK_BLUE_SMALL 92
#define GX_PIXELMAP_ID_RENESAS_LOGOMARK_WHITE_SMALL 93
#define GX_PIXELMAP_ID_R_0 94
#define GX_PIXELMAP_ID_R_1 95
#define GX_PIXELMAP_ID_R_2 96
#define GX_PIXELMAP_ID_R_3 97
#define GX_PIXELMAP_ID_R_4 98
#define GX_PIXELMAP_ID_R_5 99
#define GX_PIXELMAP_ID_R_6 100
#define GX_PIXELMAP_ID_R_7 101
#define GX_PIXELMAP_ID_R_8 102
#define GX_PIXELMAP_ID_R_9 103
#define GX_PIXELMAP_ID_SAT 104
#define GX_PIXELMAP_ID_SLASH 105
#define GX_PIXELMAP_ID_SLIDER 106
#define GX_PIXELMAP_ID_SUN 107
#define GX_PIXELMAP_ID_THU 108
#define GX_PIXELMAP_ID_TOMEI 109
#define GX_PIXELMAP_ID_TUE 110
#define GX_PIXELMAP_ID_WALLPAPER_600X800 111
#define GX_PIXELMAP_ID_WASHER_OFF 112
#define GX_PIXELMAP_ID_WASHER_ON 113
#define GX_PIXELMAP_ID_WED 114
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 115

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define DISPLAY_1_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
