/* generated vector source file - do not edit */
#include "bsp_api.h"
#include "vector_data.h"

extern void Default_Handler(IRQn_Type const irq);

BSP_DONT_REMOVE fsp_vector_t g_vector_table[BSP_ICU_VECTOR_MAX_ENTRIES]
BSP_PLACE_IN_SECTION (BSP_SECTION_APPLICATION_VECTORS) =
{ Default_Handler, /* ID:0 */
  Default_Handler, /* ID:1 */
  Default_Handler, /* ID:2 */
  Default_Handler, /* ID:3 */
  Default_Handler, /* ID:4 */
  Default_Handler, /* ID:5 */
  Default_Handler, /* ID:6 */
  Default_Handler, /* ID:7 */
  Default_Handler, /* ID:8 */
  Default_Handler, /* ID:9 */
  Default_Handler, /* ID:10 */
  Default_Handler, /* ID:11 */
  Default_Handler, /* ID:12 */
  Default_Handler, /* ID:13 */
  Default_Handler, /* ID:14 */
  Default_Handler, /* ID:15 */
  Default_Handler, /* ID:16 */
  Default_Handler, /* ID:17 */
  Default_Handler, /* ID:18 */
  Default_Handler, /* ID:19 */
  Default_Handler, /* ID:20 */
  Default_Handler, /* ID:21 */
  Default_Handler, /* ID:22 */
  Default_Handler, /* ID:23 */
  Default_Handler, /* ID:24 */
  Default_Handler, /* ID:25 */
  Default_Handler, /* ID:26 */
  Default_Handler, /* ID:27 */
  Default_Handler, /* ID:28 */
  Default_Handler, /* ID:29 */
  Default_Handler, /* ID:30 */
  Default_Handler, /* ID:31 */
  Default_Handler, /* ID:32 */
  Default_Handler, /* ID:33 */
  Default_Handler, /* ID:34 */
  Default_Handler, /* ID:35 */
  Default_Handler, /* ID:36 */
  Default_Handler, /* ID:37 */
  Default_Handler, /* ID:38 */
  Default_Handler, /* ID:39 */
  Default_Handler, /* ID:40 */
  Default_Handler, /* ID:41 */
  Default_Handler, /* ID:42 */
  Default_Handler, /* ID:43 */
  Default_Handler, /* ID:44 */
  Default_Handler, /* ID:45 */
  Default_Handler, /* ID:46 */
  Default_Handler, /* ID:47 */
  Default_Handler, /* ID:48 */
  Default_Handler, /* ID:49 */
  Default_Handler, /* ID:50 */
  Default_Handler, /* ID:51 */
  Default_Handler, /* ID:52 */
  Default_Handler, /* ID:53 */
  Default_Handler, /* ID:54 */
  Default_Handler, /* ID:55 */
  Default_Handler, /* ID:56 */
  Default_Handler, /* ID:57 */
  Default_Handler, /* ID:58 */
  Default_Handler, /* ID:59 */
  Default_Handler, /* ID:60 */
  Default_Handler, /* ID:61 */
  Default_Handler, /* ID:62 */
  Default_Handler, /* ID:63 */
  Default_Handler, /* ID:64 */
  Default_Handler, /* ID:65 */
  Default_Handler, /* ID:66 */
  Default_Handler, /* ID:67 */
  Default_Handler, /* ID:68 */
  Default_Handler, /* ID:69 */
  Default_Handler, /* ID:70 */
  Default_Handler, /* ID:71 */
  Default_Handler, /* ID:72 */
  Default_Handler, /* ID:73 */
  Default_Handler, /* ID:74 */
  Default_Handler, /* ID:75 */
  Default_Handler, /* ID:76 */
  Default_Handler, /* ID:77 */
  gtm_int_isr, /* ID:78 GTM0 INT (GTM0 Interrupt) */
  gtm_int_isr, /* ID:79 GTM1 INT (GTM1 Interrupt) */
  Default_Handler, /* ID:80 */
  Default_Handler, /* ID:81 */
  Default_Handler, /* ID:82 */
  Default_Handler, /* ID:83 */
  Default_Handler, /* ID:84 */
  Default_Handler, /* ID:85 */
  Default_Handler, /* ID:86 */
  Default_Handler, /* ID:87 */
  Default_Handler, /* ID:88 */
  Default_Handler, /* ID:89 */
  Default_Handler, /* ID:90 */
  Default_Handler, /* ID:91 */
  Default_Handler, /* ID:92 */
  Default_Handler, /* ID:93 */
  Default_Handler, /* ID:94 */
  Default_Handler, /* ID:95 */
  Default_Handler, /* ID:96 */
  Default_Handler, /* ID:97 */
  Default_Handler, /* ID:98 */
  Default_Handler, /* ID:99 */
  Default_Handler, /* ID:100 */
  Default_Handler, /* ID:101 */
  Default_Handler, /* ID:102 */
  Default_Handler, /* ID:103 */
  Default_Handler, /* ID:104 */
  Default_Handler, /* ID:105 */
  Default_Handler, /* ID:106 */
  Default_Handler, /* ID:107 */
  Default_Handler, /* ID:108 */
  Default_Handler, /* ID:109 */
  Default_Handler, /* ID:110 */
  Default_Handler, /* ID:111 */
  Default_Handler, /* ID:112 */
  Default_Handler, /* ID:113 */
  Default_Handler, /* ID:114 */
  Default_Handler, /* ID:115 */
  Default_Handler, /* ID:116 */
  Default_Handler, /* ID:117 */
  Default_Handler, /* ID:118 */
  gether_eint_isr, /* ID:119 ETH1 PIF INT */
  Default_Handler, /* ID:120 */
  Default_Handler, /* ID:121 */
  Default_Handler, /* ID:122 */
  Default_Handler, /* ID:123 */
  Default_Handler, /* ID:124 */
  Default_Handler, /* ID:125 */
  Default_Handler, /* ID:126 */
  Default_Handler, /* ID:127 */
  Default_Handler, /* ID:128 */
  Default_Handler, /* ID:129 */
  Default_Handler, /* ID:130 */
  Default_Handler, /* ID:131 */
  Default_Handler, /* ID:132 */
  Default_Handler, /* ID:133 */
  Default_Handler, /* ID:134 */
  Default_Handler, /* ID:135 */
  Default_Handler, /* ID:136 */
  Default_Handler, /* ID:137 */
  Default_Handler, /* ID:138 */
  Default_Handler, /* ID:139 */
  Default_Handler, /* ID:140 */
  Default_Handler, /* ID:141 */
  Default_Handler, /* ID:142 */
  Default_Handler, /* ID:143 */
  Default_Handler, /* ID:144 */
  Default_Handler, /* ID:145 */
  Default_Handler, /* ID:146 */
  Default_Handler, /* ID:147 */
  Default_Handler, /* ID:148 */
  Default_Handler, /* ID:149 */
  Default_Handler, /* ID:150 */
  Default_Handler, /* ID:151 */
  Default_Handler, /* ID:152 */
  Default_Handler, /* ID:153 */
  Default_Handler, /* ID:154 */
  Default_Handler, /* ID:155 */
  Default_Handler, /* ID:156 */
  Default_Handler, /* ID:157 */
  Default_Handler, /* ID:158 */
  Default_Handler, /* ID:159 */
  Default_Handler, /* ID:160 */
  Default_Handler, /* ID:161 */
  Default_Handler, /* ID:162 */
  Default_Handler, /* ID:163 */
  Default_Handler, /* ID:164 */
  Default_Handler, /* ID:165 */
  Default_Handler, /* ID:166 */
  Default_Handler, /* ID:167 */
  Default_Handler, /* ID:168 */
  Default_Handler, /* ID:169 */
  Default_Handler, /* ID:170 */
  Default_Handler, /* ID:171 */
  Default_Handler, /* ID:172 */
  Default_Handler, /* ID:173 */
  Default_Handler, /* ID:174 */
  Default_Handler, /* ID:175 */
  Default_Handler, /* ID:176 */
  Default_Handler, /* ID:177 */
  Default_Handler, /* ID:178 */
  Default_Handler, /* ID:179 */
  Default_Handler, /* ID:180 */
  Default_Handler, /* ID:181 */
  Default_Handler, /* ID:182 */
  Default_Handler, /* ID:183 */
  Default_Handler, /* ID:184 */
  Default_Handler, /* ID:185 */
  Default_Handler, /* ID:186 */
  Default_Handler, /* ID:187 */
  Default_Handler, /* ID:188 */
  Default_Handler, /* ID:189 */
  Default_Handler, /* ID:190 */
  Default_Handler, /* ID:191 */
  Default_Handler, /* ID:192 */
  Default_Handler, /* ID:193 */
  Default_Handler, /* ID:194 */
  Default_Handler, /* ID:195 */
  Default_Handler, /* ID:196 */
  Default_Handler, /* ID:197 */
  Default_Handler, /* ID:198 */
  Default_Handler, /* ID:199 */
  Default_Handler, /* ID:200 */
  Default_Handler, /* ID:201 */
  Default_Handler, /* ID:202 */
  Default_Handler, /* ID:203 */
  Default_Handler, /* ID:204 */
  Default_Handler, /* ID:205 */
  Default_Handler, /* ID:206 */
  Default_Handler, /* ID:207 */
  Default_Handler, /* ID:208 */
  Default_Handler, /* ID:209 */
  Default_Handler, /* ID:210 */
  Default_Handler, /* ID:211 */
  Default_Handler, /* ID:212 */
  Default_Handler, /* ID:213 */
  Default_Handler, /* ID:214 */
  Default_Handler, /* ID:215 */
  Default_Handler, /* ID:216 */
  Default_Handler, /* ID:217 */
  Default_Handler, /* ID:218 */
  Default_Handler, /* ID:219 */
  Default_Handler, /* ID:220 */
  Default_Handler, /* ID:221 */
  Default_Handler, /* ID:222 */
  Default_Handler, /* ID:223 */
  Default_Handler, /* ID:224 */
  Default_Handler, /* ID:225 */
  Default_Handler, /* ID:226 */
  Default_Handler, /* ID:227 */
  Default_Handler, /* ID:228 */
  Default_Handler, /* ID:229 */
  Default_Handler, /* ID:230 */
  Default_Handler, /* ID:231 */
  Default_Handler, /* ID:232 */
  Default_Handler, /* ID:233 */
  Default_Handler, /* ID:234 */
  Default_Handler, /* ID:235 */
  Default_Handler, /* ID:236 */
  Default_Handler, /* ID:237 */
  Default_Handler, /* ID:238 */
  Default_Handler, /* ID:239 */
  Default_Handler, /* ID:240 */
  Default_Handler, /* ID:241 */
  Default_Handler, /* ID:242 */
  Default_Handler, /* ID:243 */
  Default_Handler, /* ID:244 */
  Default_Handler, /* ID:245 */
  Default_Handler, /* ID:246 */
  Default_Handler, /* ID:247 */
  Default_Handler, /* ID:248 */
  Default_Handler, /* ID:249 */
  Default_Handler, /* ID:250 */
  Default_Handler, /* ID:251 */
  Default_Handler, /* ID:252 */
  Default_Handler, /* ID:253 */
  Default_Handler, /* ID:254 */
  Default_Handler, /* ID:255 */
  Default_Handler, /* ID:256 */
  Default_Handler, /* ID:257 */
  Default_Handler, /* ID:258 */
  Default_Handler, /* ID:259 */
  Default_Handler, /* ID:260 */
  Default_Handler, /* ID:261 */
  Default_Handler, /* ID:262 */
  Default_Handler, /* ID:263 */
  Default_Handler, /* ID:264 */
  Default_Handler, /* ID:265 */
  Default_Handler, /* ID:266 */
  Default_Handler, /* ID:267 */
  Default_Handler, /* ID:268 */
  Default_Handler, /* ID:269 */
  Default_Handler, /* ID:270 */
  Default_Handler, /* ID:271 */
  Default_Handler, /* ID:272 */
  Default_Handler, /* ID:273 */
  Default_Handler, /* ID:274 */
  Default_Handler, /* ID:275 */
  Default_Handler, /* ID:276 */
  Default_Handler, /* ID:277 */
  Default_Handler, /* ID:278 */
  Default_Handler, /* ID:279 */
  Default_Handler, /* ID:280 */
  Default_Handler, /* ID:281 */
  Default_Handler, /* ID:282 */
  Default_Handler, /* ID:283 */
  Default_Handler, /* ID:284 */
  Default_Handler, /* ID:285 */
  Default_Handler, /* ID:286 */
  Default_Handler, /* ID:287 */
  Default_Handler, /* ID:288 */
  Default_Handler, /* ID:289 */
  Default_Handler, /* ID:290 */
  Default_Handler, /* ID:291 */
  Default_Handler, /* ID:292 */
  Default_Handler, /* ID:293 */
  Default_Handler, /* ID:294 */
  Default_Handler, /* ID:295 */
  Default_Handler, /* ID:296 */
  Default_Handler, /* ID:297 */
  Default_Handler, /* ID:298 */
  Default_Handler, /* ID:299 */
  Default_Handler, /* ID:300 */
  Default_Handler, /* ID:301 */
  Default_Handler, /* ID:302 */
  Default_Handler, /* ID:303 */
  Default_Handler, /* ID:304 */
  Default_Handler, /* ID:305 */
  Default_Handler, /* ID:306 */
  Default_Handler, /* ID:307 */
  Default_Handler, /* ID:308 */
  Default_Handler, /* ID:309 */
  Default_Handler, /* ID:310 */
  Default_Handler, /* ID:311 */
  Default_Handler, /* ID:312 */
  Default_Handler, /* ID:313 */
  Default_Handler, /* ID:314 */
  Default_Handler, /* ID:315 */
  Default_Handler, /* ID:316 */
  Default_Handler, /* ID:317 */
  Default_Handler, /* ID:318 */
  Default_Handler, /* ID:319 */
  Default_Handler, /* ID:320 */
  Default_Handler, /* ID:321 */
  Default_Handler, /* ID:322 */
  Default_Handler, /* ID:323 */
  Default_Handler, /* ID:324 */
  Default_Handler, /* ID:325 */
  Default_Handler, /* ID:326 */
  Default_Handler, /* ID:327 */
  Default_Handler, /* ID:328 */
  Default_Handler, /* ID:329 */
  Default_Handler, /* ID:330 */
  Default_Handler, /* ID:331 */
  Default_Handler, /* ID:332 */
  Default_Handler, /* ID:333 */
  Default_Handler, /* ID:334 */
  Default_Handler, /* ID:335 */
  Default_Handler, /* ID:336 */
  Default_Handler, /* ID:337 */
  Default_Handler, /* ID:338 */
  Default_Handler, /* ID:339 */
  Default_Handler, /* ID:340 */
  Default_Handler, /* ID:341 */
  Default_Handler, /* ID:342 */
  Default_Handler, /* ID:343 */
  Default_Handler, /* ID:344 */
  Default_Handler, /* ID:345 */
  Default_Handler, /* ID:346 */
  Default_Handler, /* ID:347 */
  Default_Handler, /* ID:348 */
  Default_Handler, /* ID:349 */
  Default_Handler, /* ID:350 */
  Default_Handler, /* ID:351 */
  Default_Handler, /* ID:352 */
  Default_Handler, /* ID:353 */
  Default_Handler, /* ID:354 */
  Default_Handler, /* ID:355 */
  Default_Handler, /* ID:356 */
  Default_Handler, /* ID:357 */
  Default_Handler, /* ID:358 */
  Default_Handler, /* ID:359 */
  Default_Handler, /* ID:360 */
  Default_Handler, /* ID:361 */
  Default_Handler, /* ID:362 */
  Default_Handler, /* ID:363 */
  Default_Handler, /* ID:364 */
  Default_Handler, /* ID:365 */
  Default_Handler, /* ID:366 */
  Default_Handler, /* ID:367 */
  Default_Handler, /* ID:368 */
  Default_Handler, /* ID:369 */
  Default_Handler, /* ID:370 */
  Default_Handler, /* ID:371 */
  Default_Handler, /* ID:372 */
  Default_Handler, /* ID:373 */
  Default_Handler, /* ID:374 */
  Default_Handler, /* ID:375 */
  Default_Handler, /* ID:376 */
  Default_Handler, /* ID:377 */
  Default_Handler, /* ID:378 */
  Default_Handler, /* ID:379 */
  Default_Handler, /* ID:380 */
  Default_Handler, /* ID:381 */
  Default_Handler, /* ID:382 */
  Default_Handler, /* ID:383 */
  Default_Handler, /* ID:384 */
  Default_Handler, /* ID:385 */
  Default_Handler, /* ID:386 */
  Default_Handler, /* ID:387 */
  Default_Handler, /* ID:388 */
  Default_Handler, /* ID:389 */
  Default_Handler, /* ID:390 */
  Default_Handler, /* ID:391 */
  Default_Handler, /* ID:392 */
  Default_Handler, /* ID:393 */
  Default_Handler, /* ID:394 */
  Default_Handler, /* ID:395 */
  Default_Handler, /* ID:396 */
  Default_Handler, /* ID:397 */
  Default_Handler, /* ID:398 */
  Default_Handler, /* ID:399 */
  Default_Handler, /* ID:400 */
  Default_Handler, /* ID:401 */
  Default_Handler, /* ID:402 */
  Default_Handler, /* ID:403 */
  Default_Handler, /* ID:404 */
  Default_Handler, /* ID:405 */
  Default_Handler, /* ID:406 */
  Default_Handler, /* ID:407 */
  Default_Handler, /* ID:408 */
  Default_Handler, /* ID:409 */
  Default_Handler, /* ID:410 */
  Default_Handler, /* ID:411 */
  scif_uart_eri_isr, /* ID:412 SCIF0 ERI (Framing or Parity error) */
  scif_uart_bri_isr, /* ID:413 SCIF0 BRI (Break (BRK) or Overrun (ORER) error) */
  scif_uart_rxi_isr, /* ID:414 SCIF0 RXI (Receive data full) */
  scif_uart_txi_isr, /* ID:415 SCIF0 TXI (Transmit data empty) */
  scif_uart_tei_isr, /* ID:416 SCIF0 TEI (Transmit end) */
  Default_Handler, /* ID:417 */
  Default_Handler, /* ID:418 */
  Default_Handler, /* ID:419 */
  Default_Handler, /* ID:420 */
  Default_Handler, /* ID:421 */
  Default_Handler, /* ID:422 */
  Default_Handler, /* ID:423 */
  Default_Handler, /* ID:424 */
  Default_Handler, /* ID:425 */
  Default_Handler, /* ID:426 */
  Default_Handler, /* ID:427 */
  Default_Handler, /* ID:428 */
  Default_Handler, /* ID:429 */
  Default_Handler, /* ID:430 */
  Default_Handler, /* ID:431 */
  Default_Handler, /* ID:432 */
  Default_Handler, /* ID:433 */
  Default_Handler, /* ID:434 */
  Default_Handler, /* ID:435 */
  Default_Handler, /* ID:436 */
  Default_Handler, /* ID:437 */
  Default_Handler, /* ID:438 */
  Default_Handler, /* ID:439 */
  Default_Handler, /* ID:440 */
  Default_Handler, /* ID:441 */
  Default_Handler, /* ID:442 */
  Default_Handler, /* ID:443 */
  Default_Handler, /* ID:444 */
  Default_Handler, /* ID:445 */
  Default_Handler, /* ID:446 */
  Default_Handler, /* ID:447 */
  Default_Handler, /* ID:448 */
  Default_Handler, /* ID:449 */
  Default_Handler, /* ID:450 */
  Default_Handler, /* ID:451 */
  Default_Handler, /* ID:452 */
  Default_Handler, /* ID:453 */
  Default_Handler, /* ID:454 */
  Default_Handler, /* ID:455 */
  Default_Handler, /* ID:456 */
  Default_Handler, /* ID:457 */
  Default_Handler, /* ID:458 */
  Default_Handler, /* ID:459 */
  Default_Handler, /* ID:460 */
  Default_Handler, /* ID:461 */
  Default_Handler, /* ID:462 */
  Default_Handler, /* ID:463 */
  Default_Handler, /* ID:464 */
  Default_Handler, /* ID:465 */
  Default_Handler, /* ID:466 */
  Default_Handler, /* ID:467 */
  Default_Handler, /* ID:468 */
  Default_Handler, /* ID:469 */
  Default_Handler, /* ID:470 */
  Default_Handler, /* ID:471 */
  Default_Handler, /* ID:472 */
  Default_Handler, /* ID:473 */
  Default_Handler, /* ID:474 */
  Default_Handler, /* ID:475 */
  Default_Handler, /* ID:476 */
  Default_Handler, /* ID:477 */
  Default_Handler, /* ID:478 */
  Default_Handler, /* ID:479 */
  Default_Handler, /* ID:480 */
  Default_Handler, /* ID:481 */
  Default_Handler, /* ID:482 */
  Default_Handler, /* ID:483 */
  Default_Handler, /* ID:484 */
  Default_Handler, /* ID:485 */
  Default_Handler, /* ID:486 */
  Default_Handler, /* ID:487 */
  Default_Handler, /* ID:488 */
  Default_Handler, /* ID:489 */
  Default_Handler, /* ID:490 */
  Default_Handler, /* ID:491 */
  Default_Handler, /* ID:492 */
  Default_Handler, /* ID:493 */
  Default_Handler, /* ID:494 */
  Default_Handler, /* ID:495 */
  Default_Handler, /* ID:496 */
  Default_Handler, /* ID:497 */
  Default_Handler, /* ID:498 */
  Default_Handler, /* ID:499 */
  Default_Handler, /* ID:500 */
  Default_Handler, /* ID:501 */
  Default_Handler, /* ID:502 */
  Default_Handler, /* ID:503 */
  Default_Handler, /* ID:504 */
  Default_Handler, /* ID:505 */
  Default_Handler, /* ID:506 */
  Default_Handler, /* ID:507 */
  Default_Handler, /* ID:508 */
  Default_Handler, /* ID:509 */
  Default_Handler, /* ID:510 */
  Default_Handler, /* ID:511 */
};
